-- Online Exam System Sample Data

-- 1. Create tables
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    email VARCHAR(100) UNIQUE,
    role ENUM('student', 'admin') NOT NULL
);

CREATE TABLE IF NOT EXISTS exams (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    start_time DATETIME,
    end_time DATETIME,
    duration INT, -- in minutes
    created_by INT,
    published TINYINT(1) NOT NULL DEFAULT 0,
    FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    exam_id INT,
    question_text TEXT,
    question_type ENUM('mcq', 'written') NOT NULL,
    FOREIGN KEY (exam_id) REFERENCES exams(id)
);

CREATE TABLE IF NOT EXISTS options (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question_id INT,
    option_text VARCHAR(255),
    is_correct BOOLEAN,
    FOREIGN KEY (question_id) REFERENCES questions(id)
);

CREATE TABLE IF NOT EXISTS answers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    question_id INT,
    answer_text TEXT,
    submitted_at DATETIME,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (question_id) REFERENCES questions(id)
);

CREATE TABLE IF NOT EXISTS results (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    exam_id INT,
    score FLOAT,
    taken_at DATETIME,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (exam_id) REFERENCES exams(id)
);

-- 2. Insert sample users
-- Password is 'password' (hash generated by PHP's password_hash)
INSERT INTO users (username, password, full_name, email, role) VALUES
('admin1', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Admin User', 'admin@example.com', 'admin'),
('student1', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Student One', 'student1@example.com', 'student');

-- 3. Insert a sample exam (active for 1 hour from now)
INSERT INTO exams (title, description, start_time, end_time, duration, created_by) VALUES
('Sample Exam', 'This is a sample exam for testing.', NOW(), DATE_ADD(NOW(), INTERVAL 1 HOUR), 60, 1);

-- 4. Insert sample questions (1 MCQ, 1 written)
INSERT INTO questions (exam_id, question_text, question_type) VALUES
(1, 'What is the capital of France?', 'mcq'),
(1, 'Explain the process of photosynthesis.', 'written');

-- 5. Insert options for the MCQ (assume question_id=1)
INSERT INTO options (question_id, option_text, is_correct) VALUES
(1, 'Paris', 1),
(1, 'London', 0),
(1, 'Berlin', 0),
(1, 'Madrid', 0); 